import React from 'react';

export function Notifications() {
  return (
    <main>
      <h2>Notifications</h2>
    <div className="notification-table">
      <table>
        <thead>
          <tr>
            <th>Username</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
          <tr>
            <td>
              <img
                className="profile"
                src="IMG_1840.jpg"
                height="30px"
                width="35px"
              />
              "Username"
            </td>
            <td>"Action"</td>
          </tr>
        </tbody>
      </table>
    </div>
    </main>
  );
}